version: '3'
services:
  # exports "dockerhost" dns name to allow us to access host from nginx
  # see http://dockerhost:8080 ref in the nginx conf
  dockerhost:
    image: qoomon/docker-host
    cap_add: ['NET_ADMIN', 'NET_RAW']
    environment:
      - PORTS=8080

  nginx:
    image: nginx
    ports:
      - '443:443'
    volumes:
      - './data/nginx.conf:/etc/nginx/nginx.conf'
      - './data/cert.pem:/etc/nginx/cert.pem'
      - './data/key.pem:/etc/nginx/key.pem'
    depends_on:
      - dockerhost
